# Generated by Django 2.0.6 on 2018-06-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='recipients',
            field=models.ManyToManyField(to='fbdata.Person'),
        ),
    ]
